version: "3.9"
services:
  frontend:
    # docker-slimでイメージをビルドするため、ここではDockerfileを指定してのビルドを行いません
    # 代わりに、docker-slimで軽量化したイメージを指定し、docker-compose up -dでは軽量化されたイメージをベースにコンテナを生成します
    # @ref: ./makefiles/nuxt3.mk IMAGE_NAME_SLIM
    image: test_nuxt3.slim
    container_name: test_nuxt3
    volumes:
      - ./frontend/app:/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - web

  web:
    # docker-slimでイメージをビルドするため、ここではDockerfileを指定してのビルドを行いません
    # 代わりに、docker-slimで軽量化したイメージを指定し、docker-compose up -dでは軽量化されたイメージをベースにコンテナを生成します
    # @ref: ./makefiles/nginx.mk IMAGE_NAME_SLIM
    image: test_nginx.slim
    container_name: test_nginx
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    restart: always

